x-deploy-policy: &x-deploy-policy
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 60s
  update_config:
    order: start-first
    monitor: 60s
    parallelism: 1
    failure_action: pause
    max_failure_ratio: 0.1
  rollback_config:
    order: start-first
    parallelism: 1
    monitor: 60s
    failure_action: pause
    max_failure_ratio: 0.1

services:
  node-provisioning:
    image: ghcr.io/socheatsok78-lab/swarmshicorp-node-provisioning:main
    environment:
      - HASHICORP_NODE_PROVISIONING_DIR=/.swarmshicorp-node-provisioning
    network_mode: host
    volumes:
      - node_provisioning_data:/.swarmshicorp-node-provisioning
    deploy:
      mode: global-job

  server:
    image: ghcr.io/socheatsok78-lab/swarmshicorp-consul:1.18
    environment:
      # Cluster bootstrap configuration
      - CONSUL_RETRY_JOIN=tasks.server
      - CONSUL_ADVERTISE_INTERFACE=eth0
      # ===============================
      # DO NOT CHANGE THIS VALUES BELOW
      # ===============================
      - CONSUL_DOCKERSWARM_AUTOPILOT=true
      # Internal Docker Swarm configurations
      - DOCKERSWARM_SERVICE_ID={{.Service.ID}}
      - DOCKERSWARM_SERVICE_NAME={{.Service.Name}}
      - DOCKERSWARM_NODE_ID={{.Node.ID}}
      - DOCKERSWARM_NODE_HOSTNAME={{.Node.Hostname}}
      - DOCKERSWARM_TASK_ID={{.Task.ID}}
      - DOCKERSWARM_TASK_NAME={{.Task.Name}}
      - DOCKERSWARM_TASK_SLOT={{.Task.Slot}}
      - DOCKERSWARM_STACK_NAMESPACE={{ index .Service.Labels "com.docker.stack.namespace"}}
    command: agent -server -bootstrap-expect=3
    hostname: server-{{.Node.ID}}.svc.cluster.local
    networks:
      # eth0
      - server_network
    volumes:
      - server_data:/consul/data
      - node_provisioning_data:/.swarmshicorp-node-provisioning
    deploy:
      <<: *x-deploy-policy
      mode: global
      placement:
        constraints:
          - node.role == manager

  agent:
    image: ghcr.io/socheatsok78-lab/swarmshicorp-consul:1.18
    environment:
      # Cluster bootstrap configuration
      - CONSUL_RETRY_JOIN=tasks.server
      - CONSUL_ADVERTISE_INTERFACE=eth1
      - CONSUL_ADVERTISE_WAN_INTERFACE=eth0
      # ===============================
      # DO NOT CHANGE THIS VALUES BELOW
      # ===============================
      - CONSUL_DOCKERSWARM_AUTOPILOT=true
      # Internal Docker Swarm configurations
      - DOCKERSWARM_SERVICE_ID={{.Service.ID}}
      - DOCKERSWARM_SERVICE_NAME={{.Service.Name}}
      - DOCKERSWARM_NODE_ID={{.Node.ID}}
      - DOCKERSWARM_NODE_HOSTNAME={{.Node.Hostname}}
      - DOCKERSWARM_TASK_ID={{.Task.ID}}
      - DOCKERSWARM_TASK_NAME={{.Task.Name}}
      - DOCKERSWARM_TASK_SLOT={{.Task.Slot}}
      - DOCKERSWARM_STACK_NAMESPACE={{ index .Service.Labels "com.docker.stack.namespace"}}
    command: agent -ui
    hostname: agent-{{.Node.ID}}.svc.cluster.local
    ports:
      - published: 8500
        target: 8500
        protocol: tcp
        mode: host
    networks:
      - public_network
      - server_network
    volumes:
      - agent_data:/consul/data
      - node_provisioning_data:/.swarmshicorp-node-provisioning
    depends_on:
      - server
    deploy:
      <<: *x-deploy-policy
      mode: global
      placement:
        constraints:
          - node.role == worker

volumes:
  node_provisioning_data:
  server_data:
  agent_data:

networks:
  public_network:
  server_network:
