services:
  consul:
    image: hashicorp/consul:latest
    command:
      - agent
      - -server
      - -ui
      - -log-level=trace
      - -bootstrap-expect=1
    environment:
      - CONSUL_BIND_ADDRESS=0.0.0.0
      - CONSUL_CLIENT_ADDRESS=0.0.0.0
      - CONSUL_ADVERTISE_INTERFACE=eth0
      - CONSUL_ADVERTISE_WAN_INTERFACE=eth2
    hostname: consul-{{.Node.ID}}.svc.cluster.local
    ports:
      - "8500:8500"
    networks:
      - consul-net
      - consul-host
    configs:
      - source: docker-bootstrap.sh
        target: /docker-bootstrap.sh
        mode: 0755
    entrypoint: ["/docker-bootstrap.sh"]
    volumes:
      - consul-data:/consul/data

configs:
  docker-bootstrap.sh:
    file: ../rootfs/docker-bootstrap.sh

volumes:
  consul-data:

networks:
  consul-net:
    driver: overlay
  consul-host:
    name: host
    external: true
