services:
  server:
    image: swarmshicorp-consul:local
    # image: ghcr.io/socheatsok78-lab/swarmshicorp-consul:1.18
    command: agent -server -ui
    environment:
      # Cluster advertise address
      - CONSUL_ADVERTISE_INTERFACE=eth0
      # ===============================
      # DO NOT CHANGE THIS VALUES BELOW
      # ===============================
      # Cluster bootstrap configuration
      - CONSUL_BOOTSTRAP_EXPECT={{.Task.Slot}}
      - CONSUL_RETRY_JOIN=server
      # Node information
      - CONSUL_NODE_NAME=consul-{{.Node.ID}}
      # Internal Docker Swarm configurations
      - DOCKERSWARM_SERVICE_ID={{.Service.ID}}
      - DOCKERSWARM_SERVICE_NAME={{.Service.Name}}
      - DOCKERSWARM_NODE_ID={{.Node.ID}}
      - DOCKERSWARM_NODE_HOSTNAME={{.Node.Hostname}}
      - DOCKERSWARM_TASK_ID={{.Task.ID}}
      - DOCKERSWARM_TASK_NAME={{.Task.Name}}
      - DOCKERSWARM_TASK_SLOT={{.Task.Slot}}
      - DOCKERSWARM_STACK_NAMESPACE={{ index .Service.Labels "com.docker.stack.namespace"}}
    hostname: consul-{{.Task.Slot}}.svc.cluster.local
    ports:
      - "8500:8500"
    networks:
      consul-net:
    volumes:
      - consul-data:/consul/data
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        order: stop-first
        monitor: 120s
        parallelism: 1
        failure_action: pause
        max_failure_ratio: 0.1
      rollback_config:
        order: stop-first
        parallelism: 1
        monitor: 120s
        failure_action: pause
        max_failure_ratio: 0.1

volumes:
  consul-data:

networks:
  consul-net:
    driver: overlay
