services:
  consul:
    image: swarmshicorp-consul:local
    environment:
      - CONSUL_BIND_ADDRESS=0.0.0.0
      - CONSUL_CLIENT_ADDRESS=0.0.0.0
      - CONSUL_ADVERTISE_INTERFACE=eth0
      - CONSUL_ADVERTISE_WAN_INTERFACE=eth2
    hostname: consul-{{.Node.ID}}.svc.cluster.local
    ports:
      - "8500:8500"
    networks:
      - consul-net
      - consul-host
    volumes:
      - consul-data:/consul/data

volumes:
  consul-data:

networks:
  consul-net:
    driver: overlay
  consul-host:
    name: host
    external: true
