name: Matrix Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  # schedule:
  #   # Runs at 15:00, only on Saturday.
  #   - cron:  '0 15 * * SAT'

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate build matrix
        id: releases
        run: echo "matrix=$(jq -cr '' matrix.json)" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.releases.outputs.matrix }}

  build:
    runs-on: ubuntu-latest
    needs: generate
    strategy:
      matrix: ${{fromJson(needs.generate.outputs.matrix)}}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
          tags: type=raw,value=${{ matrix.version }}

      - name: Generate GitHub metadata
        id: github-meta
        uses: dockerbakery/github-metadata-action@v2

      - name: Build and push
        uses: docker/bake-action@v4
        env:
          VAULT_VERSION: ${{ matrix.version }}
        with:
          push: ${{ github.event_name != 'pull_request' }}
          files: |
            ./docker-bake.hcl
            ${{ steps.docker-meta.outputs.bake-file }}
            ${{ steps.github-meta.outputs.bake-file }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Docker Metadata Summary
        uses: dockerbakery/docker-metadata-summary@v1
